variables:
  IMAGE: ''
  ENABLE_CANARY: 'false'
  ENABLE_SEQUENTIAL_BUILD: 'true'

include:
  - project: sdk12/devops/ci
    ref: master
    file: templates/nodejs/ms-dataserver.gitlab-ci.yml

.node-build:
  image: docker.devops.somosdigital.io/build/node:20.9.0-12
